### PR TITLE
openmpi has gcc and not gcccore as dependency, corrected

### PR DESCRIPTION
**Pull request by planetmija**

### CODE REVIEW

**Comment by planetmija** [comment]
ok to test

**Comment by planetmija** [comment]
Ok this seems to be wrong Thiago. Test still uses old GCCcore dependency.

**Comment by thiagoabdo** [comment]
I would say that this 65b15b0  is correct
I believe that we have two other problems
One is that jenkins is without home, I believe that you mounted /home on top

**Comment by planetmija** [comment]
oh yes for a test ;)
jenkins should not use /home

**Comment by thiagoabdo** [comment]
ok to test

**Comment by thiagoabdo** [comment]
run test

**Comment by thiagoabdo** [comment]
run test.

**Comment by thiagoabdo** [comment]
The pipeline is broke now...

**Comment by planetmija** [comment]
if you see the log in /tmp it still tries gcccore :(

**Comment by planetmija** [comment]
does it test each commit for itself? this can't work because of the wrong dependency.

**Comment by thiagoabdo** [comment]
> this can't work because of the wrong dependency.

No the latest test( #28) was with the more recent commit

Jenkins needs his home right now and his home should be in every compute node, we could move his home to other place but it needs to access his home at every compilation. And he has some jenkins java files (that is way the pipeline is broken now)

**Comment by thiagoabdo** [comment]
> if you see the log in /tmp it still tries gcccore :(

But this is also true I need access to the /home to do some debuging, I will umount it and we can move that latter.

**Comment by planetmija** [comment]
OK, then it makes sense. /home/jenkins is already available for 20 min.

**Comment by thiagoabdo** [comment]
ok to test

**Comment by thiagoabdo** [comment]
ok to test

**Comment by thiagoabdo** [comment]
ok to test

**Review by thiagoabdo — COMMENTED** [review]
looks good

**Review by thiagoabdo — APPROVED** [review]

**Comment by thiagoabdo** [comment]
Was a error in the configuration of the plugin in jenkins, mybad :/

**Comment by planetmija** [comment]
np, good that you found it now ;)
when you are gone this will be much harder :(

**Pull request merged**
