### PR TITLE
New module naming scheme (lowercase hierarchical)

### PR DESCRIPTION
**Pull request by thiagoabdo**

### CODE REVIEW

**Comment by thiagoabdo** [comment]
@planetmija Can you merge this?
It is changing the naming scheme of modules to hierarchical, when merged to master will start to rebuild everything, if you do not remove the old modules before merging both will exist

**Comment by planetmija** [comment]
can't review
only merge as admin :(

**Comment by planetmija** [comment]
wait bullshit, thought there would be a button at the bottom

**Comment by planetmija** [comment]
local review sucks though

**Comment by planetmija** [comment]
I do trust your work ;)

**Pull request merged**
