### PR TITLE
added NestSimulator camel case with intelpython and new dep boost

### PR DESCRIPTION
**Pull request by planetmija**
removed nest foss lower case, was not final anyway

### CODE REVIEW

**Comment by thiagoabdo** [comment]
Yeah, but you still need to remove the module, it is going to be created to the same name of the one that is already installed

**Comment by planetmija** [comment]
> Yeah, but you still need to remove the module, it is going to be created to the same name of the one that is already installed

I did git rm or do you mean the module and software files on the server?

**Comment by thiagoabdo** [comment]
> > Yeah, but you still need to remove the module, it is going to be created to the same name of the one that is already installed
> 
> I did git rm or do you mean the module and software files on the server?

just the module files are enough

because does not matter the name of the actual easyconfig, easybuild translates it based on the contents of it (name, version and toolchain I believe)

> bio/nest-simulator/2.20.0-foss-2019b is already installed (module found), skipping

**Comment by planetmija** [comment]
ok to test

**Comment by planetmija** [comment]
ok to test

**Comment by thiagoabdo** [comment]
ok to test

**Comment by thiagoabdo** [comment]
ok to test

**Comment by thiagoabdo** [comment]
ok for test

**Comment by thiagoabdo** [comment]
test this please

**Comment by planetmija** [comment]
ok to test

**Comment by planetmija** [comment]
test this please

**Comment by planetmija** [comment]
ok to test

**Comment by planetmija** [comment]
enough tests ;)

**Pull request merged**
