### PR TITLE
New nest version for test with mkl and python /w numpy and scipy

### PR DESCRIPTION
**Pull request by planetmija**

### CODE REVIEW

**Comment by thiagoabdo** [comment]
ok to test

**Comment by thiagoabdo** [comment]
rerun test

**Comment by thiagoabdo** [comment]
retest this please

**Comment by planetmija** [comment]
test this please

**Comment by planetmija** [comment]
test this please

**Comment by planetmija** [comment]
ok to test

**Comment by planetmija** [comment]
ok to test

**Pull request merged**
